{
  "app":
    {
      "mud": {
        "host": "localhost",
        "port": "15432",
        "username": "postgres",
        "password": "1234",
        "db": "postgres"
      },
      "kafka": {
        "host": "localhost:29092,localhost:39092",
        "topic" : "test-topic,test1-topic"
      }
    }
}