{
  "app":
    {
      "mud": {
      "host": "localhost",
      "port": "15432",
      "username": "postgres",
      "password": "1234",
      "db": "postgres"
    },
    "health_check": {
      "check_translation_client": {
        "optional": true
      }
    },
    "es": {
      "omni_es_host": "http://localhost:9200",
      "bees_es_host": "http://localhost:9200",
      "index" : {
          "omnisearch_search_alias_name" : "omnisearch_search"
      }
    },
    "rabbitmq": {
        "host": "localhost"
    },
      "redis": {
          "host": "localhost",
          "port": "6379",
          "db": "0"
      }
    },
  "server": {
    "http_config": {
      "default": {
        "interface": "",
        "port": "8088",
        "shutdown_time": 20
      }
    }
  }
}