{
  "app":
    {
      "mud": {
        "host": "localhost",
        "port": "15432",
        "username": "postgres",
        "password": "1234",
        "db": "postgres"
      },
      "es": {
        "es_host": "http://localhost:9203",
        "index" : {
            "index" : "kafka_indexing"
        }
      },
      "kafka": {
        "host": "localhost:29092,localhost:39092",
        "topic" : "test-topic,test1-topic"
      }
    }
}