version: '3'
#docker-compose -f ./docker-compose.yml up or docker-compose up
name: python-flask-basic-api
services:

  fn-flask-basic-api:
    image: euiyoung/fn-flask-basic-api:es
    container_name: fn-flask-basic-api
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - 15000:5000
    volumes:
      - ${PROJECTS_DIR}/python-flask-basic:/app/FN-BEES-Services
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:15432/postgres
      - KAFKA_HOST=host.docker.internal:29092,host.docker.internal:39092
      - KAFKA_TOPIC=test-topic,test1-topic
    networks:
      - bridge
      
  fn-flask-basic-api-test:
    image: euiyoung/fn-flask-basic-api:test
    container_name: fn-flask-basic-api-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    ports:
      - 15001:5001
    volumes:
      - ${PROJECTS_DIR}/python-flask-basic:/app/FN-BEES-Services
    environment:
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:15432/postgres
      - KAFKA_HOST=host.docker.internal:29092,host.docker.internal:39092
      - KAFKA_TOPIC=test-topic,test1-topic
    networks:
      - bridge

      
networks:
  bridge:
    driver: bridge