
openapi: 3.0.0
info:
  description: Basic project with Flask , Connexion and OpenApi 3
  version: 1.0.0
  title: Connexion example
  contact:
    email: marieuig@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


servers:
  - url: http://0.0.0.0:5000/api
   
# Paths supported by the server application
paths:
  /db:
    get:
      operationId: "api.controller.api_controller.api_get"
      tags:
        - "database"
      summary: "The table data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read table list operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                # type: object
                # properties:
                #   fname:
                #     type: string
                #   lname:
                #     type: string
                #   timestamp:
                #     type: string
            
 
  
components:
  schemas:
    User:
      type: object
      properties:
        fname:
          type: string
        lname:
          type: string
        timestamp:
          type: string